### ISSUE TITLE
Same routes in different controllers problem

### ISSUE THREAD

**Issue by guiMande** [orbisgis/orbisserver#14]
It seems that it is not possible to manage the same route (/orbisserver/ows) in differents controllers as we actually have, maybe it is better to have one big controller which controls this route and all the parameters.

**Comment by SPalominos** [comment]
Yes good idea.

**Comment by ebocher** [comment]
Yes but what about if we implements over services as WMS, WFS ?

**Comment by guiMande** [comment]
For WMS and WFS, it is the same route but only the parameters (service, version, ...) that changes ?

**Comment by ebocher** [comment]
you mean about the main route URI ? /orbisserver/ows and each controllers WPS, WMS, WFS will in the future implement their own service parameters ?

**Comment by guiMande** [comment]
They all use the same main route /orbisserver/ows, but it can be just one controller for this route, so WMS and WFS will be implemented in this controller  and manage their parameters. It will be like there are 3 parts in the controller.

**Comment by ebocher** [comment]
Humm I think WMS and WFS must be implemented in separate classes because this use their own osgi bundles.
@SPalominos ?

**Comment by SPalominos** [comment]
The route `/orbisserver/ows` will be in a dedicated bundle (maybe the core-server bundle) and it should be able the add services (WPS, WMS, WFS ...).
Each  service bundle like WPS, throw OSGI, will register itself in a manager exposing all the services throw the route `/orbisserver/ows`.
