### ISSUE TITLE
Implements Execute

### ISSUE THREAD

**Issue by guiMande** [orbisgis/orbisserver#16]
Implements Execute as
`http://hostname:port/path?service=WPS&version=2.0.0&request=Execute&identifier=orbisgis:wps:official:deleteColumns&DataInputs=(DataInputType Object)&DataOutput=(DataOutput object)&response=document&mode=auto` ?

- tests + javadoc.

**Comment by ebocher** [comment]
@SPalominos  Are you ok with this syntax ???

**Comment by guiMande** [comment]
It is just for DataInputs and DataOutputs that I don't know how do you want to write it in the request.

**Comment by guiMande** [comment]
The only response to a Execute method is a StatusInfo object and not a document or a Raw data ?

**Comment by SPalominos** [comment]
For the `execute` request (as explained in the standard), it is not a HTTP GET request but a POST one.
For the `execute` response, we always returns a `StatusInfo` object.

**Comment by guiMande** [comment]
Ok i'll work on this.

**Comment by guiMande** [comment]
Do I have to do like in OrbisWPS and load a ExecuteRequest.xml file and edit it ?

**Comment by SPalominos** [comment]
As the size of an xml file containing an execute request is very small, I think you can write it on your own.

**Comment by guiMande** [comment]
Okay. Should I do a formulary on a web page to set parameters of the execution or not ?

**Comment by SPalominos** [comment]
Of course!

**Comment by guiMande** [comment]
How does the URI of the POST request looks like after loads a execute request ?

**Comment by guiMande** [comment]
For inputs data, is that ok if they are separate with &, and the String[] by ; ?

**Comment by SPalominos** [comment]
Yes

**Comment by guiMande** [comment]
Ok, and for booleans data, is that ok if the data looks like `true` or `false`, we create the booleans parameters in the code, i mean any other input data looks like this ?

**Comment by SPalominos** [comment]
Yes, there will be no problem as this kind of case is taken into account in the wpsServer

**Comment by guiMande** [comment]
For boolean inputs, i create a boolean in terms of the input data and add it to the Data object, but when i test i get this error `impossible de sérialiser le type "java.lang.Boolean" en tant qu'élément car il lui manque une annotation @XmlRootElement`, any idea ?

**Comment by SPalominos** [comment]
boolean is a literal data, so create a literal data.

**Comment by guiMande** [comment]
that's what i do, i create the boolean and add it to the list of Content of a Data object.

**Comment by SPalominos** [comment]
Convert it to a String

**Comment by guiMande** [comment]
I found the solution, it's ok now.

**Comment by guiMande** [comment]
For the output parameter which is generally the output message, which attribute in a OutputDefinitionType correspond to that parameter ?
