### ISSUE TITLE
Display the results of the GetCapabilities method on the HTML page

### ISSUE THREAD

**Issue by guiMande** [orbisgis/orbisserver#2]
The results are displaying in the terminal actually, the next step is to display those results on the html page. For that, IndexController and index.html will be modified. (add and display a list)

**Comment by SPalominos** [comment]
Great, do not forget to assign yourself to the issue if you are working on it.

**Comment by ebocher** [comment]
I think the first way is to return a xml from the GetCapabilities http request.

**Comment by ebocher** [comment]
A good way to start will be to list all http requests

**Comment by guiMande** [comment]
The GetCapabilities http request return the corresponding xml file correctly but Html files and JS scripts are not used to.

**Comment by SPalominos** [comment]
Linked to the issue #3
