### ISSUE TITLE
Home template

### ISSUE THREAD

**Issue by Vquillien** [orbisgis/orbisserver#29]
The first page of the web site.

Element : 
- [X] elements of the base page
- [x] make the lateral nav be invisible :
     - [X] add collapse animation
     - [x] adapt the bar width to the page width with 3 aspects: normal, only icon, hidden
     - [X] adapt the bar heigth to the page height

Mechanism : 
- [X] login
- [X] introduction of the web site

**Comment by SPalominos** [comment]
Working of the user menu
