### ISSUE TITLE
Implements GetCapabilities

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#3]
Implements the following GetCapabilities and returns its corresponding xml file

```
http://localhost:8080/orbisserver/ows?
  service=WPS&
  version=2.0.0&
  request=GetCapabilities

```

Don't forget to add tests to cover all syntax errors

@guiMande, @SPalominos

**Comment by guiMande** [comment]
Is it ok if GetCapabilities method is implemented and its corresponding xml file is return only with Java in IndexController ?

**Comment by SPalominos** [comment]
Yes, you have to get the server answer by calling `wpsServer.callOperation(InputStream xml)`. Then you will give the result in two ways :
- the raw xml as answer to a HTTP GET request.
- a web page in html with the process list in a human readable way.

**Comment by ebocher** [comment]
Done ?

**Comment by guiMande** [comment]
Yes.

**Comment by SPalominos** [comment]
Ok, so I close the issue.
