### ISSUE TITLE
Login template

### ISSUE THREAD

**Issue by Vquillien** [orbisgis/orbisserver#30]
This page allow a user to input his user name and his password.

Element :
- [X] a form 
  - label "user name"
  - input 
  - label "password"
  - input 

Mechanism : 
- [X] check the username and the password
- [X] adds session mechanism
- [ ] communicate the password from the web client to the server with security with SSL cert

**Comment by SPalominos** [comment]
Working on session.

**Comment by SPalominos** [comment]
Working on the aspect of the login modal
