### ISSUE TITLE
Implements DescribeProcess

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#4]
Implements DescribeProcess and return the corresponding xml file

```
http://hostname:port/path?service=WPS&version=2.0.0&request=DescribeProcess&identifier=buffer,viewshed
```

```
http://hostname:port/path?service=WPS&version=2.0.0&request=DescribeProcess&identifier=ALL
```

+ tests, + javadoc

@guiMande, @SPalominos

**Comment by SPalominos** [comment]
Yes, the `service=WPS` and `version=2.0.0` are always the same but `identifier` changes according to the process requested.

**Comment by guiMande** [comment]
Instead of using the method createGetCapabilities from ObjectFactory, here which method should be used ?

**Comment by ebocher** [comment]
What did you mean exactly ?

**Comment by guiMande** [comment]
I was a bit lost with getting the xml file corresponding to the DescribeProcess method, should I set the identifier of a new DescribeProcess object with identifiers from the list of ProcessSummaryType already created and then display the ProcessOffering obtained at the end ?
`ProcessOfferings describeProcess(DescribeProcess describeProcess);`

**Comment by ebocher** [comment]
As we have already discussed in the last meeting, you must send one PR by issue. It will be more easier for us to drive you.

**Comment by guiMande** [comment]
WPS Operations do not have identifiers ?

**Comment by SPalominos** [comment]
If you mean identifiers like the identifier in the ProcessDecriptionType, no, they don't have identifier. Otherwise, I don't understand what you mean.

**Comment by guiMande** [comment]
For the identifier of DescribeProcess, how do you set it ? There is no setter and the attribute is protected.

**Comment by SPalominos** [comment]
```java
describeProcess.getIdentifier().add(yourIdentifierHere)

**Comment by guiMande** [comment]
Oh I thought I tried it my bad, thank you.

**Comment by guiMande** [comment]
I have the the xml response of the DescribeProcess method which is the ProcessDescriptionType of the process. Is that good or do I have to display something else (ProcessOffering/ProcessOfferings) ?

**Comment by guiMande** [comment]
HTTP Requests look like this :
`http://localhost:8080/orbisserver/ows?service=WPS&version=2.0.0&request=DescribeProcess&identifier=file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy`
or 
`http://localhost:8080/orbisserver/ows?service=WPS&version=2.0.0&request=DescribeProcess&identifier=orbisgis:wps:official:deleteColumns`
Is that ok for the first one to have this kind of identifier ? It should be groovy scripts from OrbisWPS no ?

**Comment by ebocher** [comment]
We must support only this one
```
http://localhost:8080/orbisserver/ows?service=WPS&version=2.0.0&request=DescribeProcess&identifier=orbisgis:wps:official:deleteColumns
```

**Comment by SPalominos** [comment]
You should accpt url of this kind `HOST?service=SERVICE&version=VERSION&request=REQUEST&identifier=IDENTIFIER`, no matter what is put in HOST, SERVICE, VERSION, REQUEST and IDENTIFIER. Then you check field one by one to know which service is asked, with wich version, with which request ...

I your first case, the identifier is  `file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy` which is the URI of the script, which is also used as identifier as an URI is unique, so does the identifier.

**Comment by guiMande** [comment]
For Unit tests, there is a problem, the list of identifiers is empty for the tests, this list is created when the server is launched so in Unit tests it does not exist.

**Comment by guiMande** [comment]
Nevermind, i found the solution.

**Comment by ebocher** [comment]
Done ?

**Comment by guiMande** [comment]
Yes.
