### ISSUE TITLE
Implements GetStatus

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#5]
Implements GetStatus as

```
http://hostname:port/path?service=WPS&version=2.0.0&request=GetStatus&jobid= FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66

```

@guiMande, @SPalominos

**Comment by SPalominos** [comment]
Yes, the `service=WPS` and `version=2.0.0` are always the same but `jobid` changes according to the job requested.

**Comment by guiMande** [comment]
The user knows the jobId after seeing it from the execute response right ?

**Comment by SPalominos** [comment]
After the execute request, you get a GetStatus response which contains the jobId
