### ISSUE TITLE
Implements GetResult

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#6]
Implements GetResult as

```
http://hostname:port/path?service=WPS&version=2.0.0&request=GetResult&jobid= FB6DD4B0-A2BB-11E3-A5E2-0800200C9A66
```

@guiMande, @SPalominos

**Comment by SPalominos** [comment]
Yes, the `service=WPS` and `version=2.0.0` are always the same but `jobid` changes according to the job requested.
