### ISSUE TITLE
Cannot compile master

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#78]
Execute on core-server

 mvn wisdom:run

returns

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.944 s
[INFO] Finished at: 2017-09-27T22:12:57+02:00
[INFO] Final Memory: 26M/375M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project coreserver: Could not resolve dependencies for project org.orbisgis.orbisserver:coreserver:wisdom:1.0-SNAPSHOT: Could not find artifact org.orbisgis.orbisserver:wpsservice:jar:1.0-SNAPSHOT in OrbisGIS (http://repo.orbisgis.org) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by SPalominos** [comment]
Does the problem subsist?
