### ISSUE TITLE
Extend widsom-jdbc to support H2GIS

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisserver#9]
Extend widsom-jdbc module to support the last H2 and H2GIS libraries.

**Comment by nicolas-f** [comment]
? 
Why not use @reference with datasource instance like all components in OrbisGIS ?

Does wisdom support declarative services ?

**Comment by SPalominos** [comment]
Wisdom-framework have it's own strategy to manage data sources with the project [Wisdom-JDBC](https://github.com/wisdom-framework/wisdom-jdbc) (It already have a H2 database). I have done the changes to add and H2GIS database on a fork of the Wisdom-JDB repository. I will do a PR as soon as possible.

**Comment by SPalominos** [comment]
Issue out of date.
